<section class="container" data-ng-controller="Login">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3">
            <h1>Login</h1>
        </div>
    </div>
    <form>
        <div class="row">
            <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 form-group">
                <label>Email Address</label>
                <input type="text" class="form-control" data-ng-model="user.email" />
            </div>
            <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 form-group">
                <label>Password</label>
                <input type="password" class="form-control" data-ng-model="user.password" />
            </div>
            <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 checkbox text-right">
                <label>
                    <input type="checkbox"
                        data-ng-model="user.remember"
                        data-ng-true-value="true"
                        data-ng-false-value="false" />Remember Me
                </label>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 text-right">
                <button type="submit" class="btn btn-success"
                data-ng-disabled="loggingIn"
                data-ng-click="login()">Login</button>
            </div>
        </div>
    </form>
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3">
            <p><a href="/forgot">Forgot Password</a></p>
        </div>
    </div>
</section>

<script type="text/javascript" src="/app/controllers/Login.js"></script>