<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Phalcon/Angular/Bootstrap</title>
        <style type="text/css">
            [ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak {
                display: none !important;
            }
        </style>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        
        <!-- Bootstrap -->
        <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>
        <link href="/lib/jquery-ui/jquery-ui.min.css" rel="stylesheet"/>
        <link href="/css/style.css" rel="stylesheet"/>
        
        <!-- jQuery -->
        <script src="/lib/jquery/jquery.min.js"></script>
        
        <!-- Angular main files -->
        <script type="text/javascript" src="/lib/angular/angular.min.js"></script>
        <script type="text/javascript" src="/lib/angular/angular-sanitize.min.js"></script>
        <script type="text/javascript" src="/app/app.js"></script>
        
        <!-- BootStrap -->
        <script src="/lib/bootstrap/js/bootstrap.min.js"></script>
    </head>
    <body data-ng-app="Bootstrap">
        <header data-ng-controller="MainMenu">
            <nav class="navbar navbar-default" role="navigation">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/"><img src="/img/logo.png" /></a>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li data-ng-if="user_loaded && !user" data-ng-cloak>
                                <a href="/create-account">Create Account</a>
                            </li>
                            <li data-ng-if="user_loaded && !user" data-ng-cloak>
                                <a href="/login">Login</a>
                            </li>
                            <li data-ng-if="user_loaded && user" data-ng-cloak>
                                <a href="/secure">Secure Page</a>
                            </li>
                            <li class="dropdown" data-ng-if="user_loaded && user" data-ng-cloak>
                                <a href="/users/view/{{user.id}}" class="dropdown-toggle" data-toggle="dropdown">{{user.email}} <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li data-ng-if="user.role_id == 2"><a href="/admin">Admin</a></li>
                                    <li><a href="/logout">Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container content" data-ng-controller="Base">
            <div class="container global-message">
                <div class="row">
                    <div class="col-xs-12 col-md-4 col-md-offset-4">
                        <div data-ng-show="errorMessage != ''" data-ng-cloak>
                            <div class="alert alert-danger">
                                <button type="button" class="close" data-ng-click="errorMessage=''">
                                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                                </button>
                                <div data-ng-bind-html="errorMessage"></div>
                            </div>
                        </div>
                        <div data-ng-show="successMessage != ''" data-ng-cloak>
                            <div class="alert alert-success">
                                <button type="button" class="close" data-ng-click="successMessage=''">
                                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                                </button>
                                <div data-ng-bind-html="successMessage"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php echo $this->getContent(); ?>
        </div>
        <footer>
            Footer 
        </footer>
        <script type="text/javascript" src="/app/shared/directives/directives.js"></script>
        <script type="text/javascript" src="/app/shared/services/Util.js"></script>
        <script type="text/javascript" src="/app/shared/services/CallCenter.js"></script>
        <script type="text/javascript" src="/app/shared/controllers/MainMenu.js"></script>
        <script type="text/javascript" src="/app/shared/controllers/Base.js"></script>
    </body>
</html>